In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt


# DATA SET1

In [3]:
data = pd.read_csv('AFeb.csv')
data

Date     Open     High      Low    Close
0    1-Feb-17  8841.67  9005.08  8812.18  8999.55
1    2-Feb-17  9015.10  9050.42  8978.42  9027.71
2    3-Feb-17  9043.01  9055.86  9007.34  9037.90
3    6-Feb-17  9074.43  9119.20  9072.04  9099.99
4    7-Feb-17  9108.50  9115.25  9038.74  9068.87
5    8-Feb-17  9087.39  9103.37  9020.90  9079.78
6    9-Feb-17  9096.18  9133.19  9032.39  9091.71
7   10-Feb-17  9112.31  9130.69  9076.42  9094.26
8   13-Feb-17  9124.52  9129.88  9050.79  9102.88
9   14-Feb-17  9116.42  9116.67  9066.18  9085.37
10  15-Feb-17  9069.52  9095.24  8986.88  8998.05
11  16-Feb-17  9015.30  9077.60  8988.78  9073.18
12  17-Feb-17  9166.36  9182.50  9102.86  9124.02
13  20-Feb-17  9131.51  9192.82  9112.87  9187.23
14  21-Feb-17  9205.16  9241.70  9184.52  9229.14
15  22-Feb-17  9248.02  9276.18  9217.10  9235.46
16  23-Feb-17  9247.56  9289.71  9229.60  9239.67
17  27-Feb-17  9244.08  9255.62  9194.20  9200.98
18  28-Feb-17  9204.06  9225.20  9178.69  9190.73

In [4]:
reg = linear_model.LinearRegression()
reg.fit(data[['Open','High','Low']],data.Close)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
reg.coef_

array([-0.69934776,  0.88535108,  0.69439377])

In [6]:
reg.intercept_

1089.9624167110114

In [7]:
reg.predict([[12345,29999,1000]])

array([19710.5551962])

In [8]:
reg.predict([[1000,1001,999]])

array([1970.55047057])

# DATA SET 2

In [9]:
data = pd.read_csv('hiring.csv')
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [10]:
#Filling the null values with median
test_score_median = data.test_score.median()
data.test_score = data.test_score.fillna(test_score_median)
data


experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [11]:
reg = linear_model.LinearRegression()
reg.fit(data[['experience','test_score','interview_score']],data.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [13]:
reg.intercept_

17737.26346433771

In [16]:
reg.predict([[0,10,7]])



array([51631.00436681])

In [15]:
reg.predict([[5,5,5]])

array([52056.76855895])

In [17]:
reg.predict([[2,5,5]])

array([43617.90393013])

# DATA SET 3

In [18]:
data = pd.read_csv('house_pricing.csv')
data.head()

MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  LotShape  \
0           9         3           65     8450       1      1         3   
1           4         3           80     9600       1      1         3   
2           9         3           68    11250       1      1         0   
3          10         3           60     9550       1      1         0   
4           9         3           84    14260       1      1         0   

   LandContour  Utilities  LotConfig  ...  PoolArea  PoolQC  Fence  \
0            3          0          4  ...         0       3      4   
1            3          0          2  ...         0       3      4   
2            3          0          4  ...         0       3      4   
3            3          0          0  ...         0       3      4   
4            3          0          2  ...         0       3      4   

   MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0            1        0       3    2008         8              4     208500  
1            1        0       8    2007         8              4     181500  
2            1        0      11    2008         8              4     223500  
3            1        0       3    2006         8              0     140000  
4            1        0       2    2008         8              4     250000  

[5 rows x 80 columns]

In [19]:
reg = linear_model.LinearRegression()
reg.fit(data[['MSSubClass','MSZoning','LotFrontage','LotArea','YrSold','SaleType','SaleCondition']],data.SalePrice)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
reg.coef_

array([ 7.12911271e+02, -1.78258083e+04,  3.76203498e+02,  1.74509256e+00,
       -1.19820679e+03, -3.75287381e+03,  1.50386623e+04])

In [21]:
reg.intercept_

2571227.833979728

In [23]:
reg.predict([[10,3,80,11250,2010,3,2]])

array([185031.14706757])